
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 20 18:47:34 BRT 2014
//----------------------------------------------------

package br.com.johnidouglas.frontendcompiler.one;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 9;
  public static final int SUMA = 6;
  public static final int EOF = 0;
  public static final int ASIGN = 5;
  public static final int PARENC = 2;
  public static final int IF = 4;
  public static final int PARENA = 3;
  public static final int ID = 10;
  public static final int DIV = 8;
  public static final int error = 1;
  public static final int MULTP = 7;
}

