
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 20 21:54:38 BRT 2014
//----------------------------------------------------

package br.com.johnidouglas.frontendcompiler.two;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _FALSE = 4;
  public static final int _PONTO_E_VIRGULA = 5;
  public static final int _TRUE = 3;
  public static final int _SEPARADOR_BOOL = 6;
  public static final int _WHILE = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

