
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 07 12:33:56 BRT 2014
//----------------------------------------------------

package sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ATRIBUICAO = 10;
  public static final int SE = 12;
  public static final int VERDADEIRO = 11;
  public static final int INICIO = 2;
  public static final int EOF = 0;
  public static final int FIM = 3;
  public static final int MULTIPLICACAO = 9;
  public static final int NUMERO = 7;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int PONTO_FLUTUANTE = 13;
  public static final int FACA = 6;
  public static final int PARA = 4;
  public static final int ATE = 5;
}

